//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySuperMarket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT_ATTRIBUTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCT_ATTRIBUTE()
        {
            this.PLAN = new HashSet<PLAN>();
            this.PRODUCT = new HashSet<PRODUCT>();
        }
    
        public string PRODUCT_ID { get; set; }
        public string SUPPLIER_ID { get; set; }
        public string PRODUCT_NAME { get; set; }
        public Nullable<int> EXP { get; set; }
        public Nullable<long> PURCHASE_PRICE { get; set; }
        public Nullable<long> SELL_PRICE { get; set; }
        public Nullable<int> TOTAL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PLAN> PLAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCT> PRODUCT { get; set; }
        public virtual SUPPLIER SUPPLIER { get; set; }
    }
}
