//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySuperMarket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIP
    {
        public string VIP_ID { get; set; }
        public string EMPLOYEE_ID { get; set; }
        public Nullable<short> CREDITS { get; set; }
        public string VIP_NAME { get; set; }
        public string SEX { get; set; }
        public string PHONE_NUMBER { get; set; }
    
        public virtual EMPLOYEE EMPLOYEE { get; set; }
    }
}
